### PR TITLE
Fixed typos

### PR DESCRIPTION
**Pull request by garyritchie**

### CODE REVIEW

**Comment by davelab6** [comment]
**AWESOME!!** Thanks @garyritchie

**Comment by davelab6** [comment]
@garyritchie I'm curious to hear your thoughts about what information you feel is missing from the book so far? :)

**Comment by garyritchie** [comment]
Thanks @davelab6. I stumbled across this resource while getting back to some works-in-progress. I still consider myself a student but when I _do_ have some thoughts where would be a good place to voice them?

BTW I'm just getting started. I'll be working through the book as I work through my font so I expect to submit more pull requests.

**Comment by davelab6** [comment]
> when I do have some thoughts where would be a good place to voice them?

The issue tracker for this project :)

> I expect to submit more pull requests.

Awesome! What city are you based in? You might like to attend one of the craftingtype.com workshops I'm involved in, or even help me put one on in your city next year :)

**Comment by garyritchie** [comment]
Pittsburgh, Pennsylvania -- and I'm very interested to have your workshop here in my city.  I saw the Chicago and Boston schedules but was not up for juggling everything to make it happen with work and all. Good luck in Chicago, by the way; let's talk about Pittsburgh when you return.

**Comment by davelab6** [comment]
Great man! drop a note to info@craftingtype.com and the collective will look into it :)

**Comment by garyritchie** [comment]
Invite sent to the collective.

**Pull request merged**
