### PR TITLE
Translation to Portuguese - Brasil

### PR DESCRIPTION
**Pull request by marcelommp**
Hello, I'm working in a translation of this great Book to Portuguese. It's for my _Tipografia Libre_ classes and a personal strategy to engage some alumni in a collaborative project. Do you think it could incorporated to the main website?

Cheers

### CODE REVIEW

**Comment by davelab6** [comment]
AWESOME!! When can this be merged? :)

**Comment by JoesCat** [comment]
Hi @marcelommp would you be interested in helping to translate some of FontForge's menus and prompts?
If yes, we could help setup a "large" textfile that could be translated using a plain-text editor.
To give you an idea of the file-size, the most recent translations are fr.po in this directory:
https://github.com/fontforge/fontforge/tree/master/po

**Comment by davelab6** [comment]
@marcelommp thanks for this! Is this ready to merge?

**Comment by marcelommp** [comment]
Hey @davelab6 I need to review,and remember where I stopped and finish all sections!

**Comment by marcelommp** [comment]
@JoesCat I'll take a big look, this is something I really interested to fix.

**Comment by aryelgois** [comment]
Hi, I have restarted the Portuguese translation, with some friends.

I looked into your fork and some other branches to see what should be done. I noticed you copied all images into your pt-BR/, but fr-FR/ does not have them.

And since just a few pages where translated, I decided to start from scratch. It would be nice if we could work together, since I want the documentation fully translated for this semester (I can dream  :stuck_out_tongue:)

**Comment by marcelommp** [comment]
Hello @aryelgois , I was reviewing my files and realized the **_what is a font_** section was the only one I finished. 

Take a look: 
https://github.com/marcelommp/designwithfontforge.com/blob/aba01d068dfd67135f32b61b24c53496a9ff867d/pt-BR/What_Is_a_Font.md

So, we can work together using this branch if you want, starting with the _**Introduction**_ section, I don't remember why I started by the second item...anyway it's done.

**Comment by aryelgois** [comment]
Yeah, but I won't lie: I used your translation for that section. :p

I would like to keep the work on [my branch](https://github.com/aryelgois/designwithfontforge.com/tree/brazilian-portuguese/pt-BR). Five pages are already translated, one is almost done and two need a review. I am trying to track things [here](https://github.com/aryelgois/designwithfontforge.com/tree/translation-track), but I am having other ideas.

Oh, there are [some branches](https://github.com/aryelgois/designwithfontforge.com/network) not merged yet. I'm trying to do my best with commit history :)

After the next merge, I'll pull the changes from gh-pages.

**Comment by marcelommp** [comment]
I’ll be happy to join your work at this moment and concentrate to help the review of the typographycal terms, since you and your team are comfortable with the massive english content. Great Job!

**Comment by aryelgois** [comment]
Thank you very much @marcelommp. And I will add you as a collaborator.

So.. could you focus in the Glossary? But first please translate "Underhangs and Overshoots", I have no idea how to translate that

**Comment by JoesCat** [comment]
Glad to read you have an interest in making a PT-BR translation.

If you think you can use the pt.po file, go ahead, if you think there are enough differences that it warrants making a separate pt-br.po file, then you will need to "git add po/pt-br.po" the new file.
I recommend making a branch and not working on main/master branch, this way it's easier to handle when it comes to merging, or if it's a real mess, deleting the branch.
Here's some reading to help: https://github.com/fontforge/fontforge/issues/2769
If you are not a developer and need help setting-up a fresh file to start with - just ask.
If you get stuck, ask questions on the sourceforge user mailing list as there are translators/authors who have gone through this - these are big files, so it's also all okay to do chunks at a time. :-)

**Comment by jrbastien** [comment]
I don't know how different is the Brazilian Portuguese from the one from Portugal but I would recommend that you create a PT-PT version for now.  Especially for "Design With Fontforge".

I'm personally from Canada but did not created the FR-CA version but rather the FR-FR version for a broader audience.

You can always copy the pt-pt.po file to pt-br.po and make your edits once you are done with the base po file.  But bear in mind that this po file has more than 7000 strings!

**Comment by marcelommp** [comment]
@aryelgois About "Underhangs and Overshoots". Overshoots= **Ajuste Óptico** but Underhands I probably use Linha de rebaixamento. But I have to ask to more type freaks. I'll do that and use it in the glossary.

**Comment by marcelommp** [comment]
@aryelgois Curvas excedentes e Compensação Ótica.

**Comment by davelab6** [comment]
@marcelommp ready to be merged? :)

**Comment by marcelommp** [comment]
@davelab6 just need to understand what's happening with this project and then get back to me :/

**Comment by davelab6** [comment]
Okay cool - just let me know when to merge :)

**Comment by JoesCat** [comment]
Hi @marcelommp, in terms of:

> @davelab6 just need to understand what's happening with this project and then get back to me :/

...open source development tends to go in bursts if you follow any individual developer.
...there can be periods where you see a lot of activity, a time where breaks are taken, and times when other things must take priority.
When a project is large, it is harder to see this as it appears active all the time - but it is also there if you follow any individual developer.
When projects become more specific and less general they have smaller groups of developers, and these development cycles are easier to see and notice.
If I understand what you say, I would say - don't panic if nothing appears to happen for 2 years.
Here is an example where you see numbers going up and down, including zero too: https://sourceforge.net/p/fontforge/mailman/fontforge-devel/

My suggestion is - measure FontForge progress in months, not days.
If you have the time now, AND you think you can get this ready (when you have time now), you are further ahead, because maybe later when activity happens here at a speed that says "active", you might be in your own phase where - for you - other things must take priority  ;-)

Hope this helps.

**Comment by marcelommp** [comment]
Hey Joe 😀
Thanks for the great explanation. I think my phrase wasn’t clear when I said get back to me. It was more like...I don’t remember where I stopped, I can’t understand how the other guys are working and I need some help to get back to Git like a pro. Helpfully I have a friend to help me whit this issue in person... and I think this whole thing just make me confuse because I started a project, then another guys created another project using my initial sketches and finally I became a collaborator of this second project. So I just need to get back to work with this guys because now I have some time.
Cheers :)

**Comment by ctrlcctrlv** [comment]
I just went through and closed all stale issues. This one was not closed because a significant amount of work was done, it's just abandoned by @marcelommp. Another Portuguese speaker is welcome to translate it. (I'm not sure that we necessarily need different Brazil and Portugal versions, but of course, will leave that to the natives. I'd say that if it's 99% understandable, and you can use words likely to be understood by both countries, please do that and let's have one Portuguese version. [If one is good enough for Portuguese Wikipedia](https://en.wikipedia.org/wiki/Portuguese_Wikipedia#History), it ought to be good enough for us.)

**Comment by JoesCat** [comment]
I merged-in what was made so far.
The first several pages upto but not including "Drawing with spiro" should be up to date and in sync with the other language pages.

**Comment by JoesCat** [comment]
Closing this pull-request as done!

Hi @marcelommp (and others interested in helping) - this may help you if you are interested in helping fix some of the chapters since there are pages that have been updated since then and now.

Read this first #253 so that you can maintain a sync with the main trunk.

**Pull request closed without merging**
