### PR TITLE
Updating precompressed/info_ps_names.png to show real world values (compressed)

### PR DESCRIPTION
**Pull request by chakler**
see #84

### CODE REVIEW

**Comment by larsenwork** [comment]
Why does the screenshot need to be that big? 
Would be annoying for people with low res screens - I'd suggest making the window smaller before taking the screenshot

**Comment by chakler** [comment]
@davelab6 What do you think?

**Comment by davelab6** [comment]
Isn't the image scaled by the CSS?

The image got bigger because its taken on a Retina macbook pro. So it will look better on such high resolution screens, and CSS will scale it down for people with lower resolution screens, or on mobile, etc.

**Comment by larsenwork** [comment]
They will.

But the image is still non-retina 820px wide. At maximum width the images on the webpage are 850px wide and becomes 690px when your screen resolution is <1160px so the text will be very small on many displays.

This is obviously a non issue for most images but screenshots of UI => small text.

**Comment by davelab6** [comment]
Ah yes I see. I think it would be best if you could make new screenshots with your current awesome theme :)

**Comment by larsenwork** [comment]
Hehe...I will do, but maybe we should wait until @frank-trampe has updated the cvpalette and then update all the UI screenshots in designwithfontforge so that the screenshots matches the latest release.

**Comment by davelab6** [comment]
Sounds good. I'll close this, then. Thanks to you both for your efforts!!

**Comment by chakler** [comment]
Great! Let me know if you need help again for compressing the image :)

**Pull request closed without merging**
