### PR TITLE
Update Glossary.md

### PR DESCRIPTION
**Pull request by KrasnayaPloshchad**
Update translation, some of them bsaed on https://www.typeisbeautiful.com/2016/09/10968/

### CODE REVIEW

**Comment by jrbastien** [comment]
I can't evaluate how good is this translation but thanks for this.

I have the following observations:

- Why is the Alphabet description and other links referring to the English Wikipedia page?  I would think the Alphabet exist in any language.  For instance: [https://zh.wikipedia.org/wiki/%E5%AD%97%E6%AF%8D%E7%B3%BB%E7%B5%B1](https://zh.wikipedia.org/wiki/%E5%AD%97%E6%AF%8D%E7%B3%BB%E7%B5%B1).  Just curious!

- Could you also review the different commits that were made to the Glossary since February 2016?  You will see that multiples corrections were made to the English version: broken links, weights organized in table, etc...  The Chinese version would benefit from them too.  See [here](https://github.com/fontforge/designwithfontforge.com/commits/gh-pages/en-US/Glossary.md).  If you click on the hash code (3ce0762 for instance), you can see all the changes that were made to the glossary.  

Thanks for you help.

**Comment by davelab6** [comment]
@KrasnayaPloshchad thanks for this and @jrbastien thanks for the careful review! :)

**Comment by KrasnayaPloshchad** [comment]
@jrbastien Thanks for your digging up, I will do it if I have a chance.

**Comment by JohnWong** [comment]
Thank you.

谢谢你的翻译。对字体方面了解不够多，我之前的翻译真的太烂了^_^

**Pull request merged**
