### PR TITLE
Italian translation

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by davelab6** [comment]
@BeforeSpring AWESOME!!! When can this be merged? :)

**Comment by JoesCat** [comment]
Hi @BeforeSpring would you be interested in helping to update some of FontForge's menus and prompts?
Inside the FontForge po directory, there is an existing Italian file which we can bring up-to-date so you can edit it further. To give you an idea of estimated file-size, the most recent translations are fr.po in this directory:
https://github.com/fontforge/fontforge/tree/master/po

**Comment by davelab6** [comment]
@BeforeSpring shall I merge this?

**Comment by davelab6** [comment]
@beforespring I was happy to merge :)

**Pull request closed without merging**
