### PR TITLE
Update Numerals.md

### PR DESCRIPTION
**Pull request by keevee09**
Fixed a few typos.
I am unsure of the very last sentence on this page. Should it be exhibiting the "letter o, capital O, zero, 1, 2, 3, etc" rather than repeating "zero"?

### CODE REVIEW

**Comment by davelab6** [comment]
Thanks! I have added you to the fontforge website team so you can merge your own pull requests, or if you like, work on the sites directly :)

**Comment by keevee09** [comment]
Thanks Dave,
I'm only learning fontforge so my edits will be mostly grammar and style
issues, seldom content :)

I've got spiro working from the master source
(https://github.com/fontforge/libspiro) now! Joe replied to my bug request.

**Comment by davelab6** [comment]
That's still an awesome contribution @keevee09 - do you have any graphics experience? Similar to grammar fixups, making the images all in the same style, and adding more screenshots to illustrate things, would be REALLY AWESOME and not require any 'content' contributions...

Thanks so much @JoesCat - super appreciate it!

**Comment by keevee09** [comment]
I've had some experience in that area, yes. I'll look at what I can do
with my 'critical eye' while reading through it ;)

**Pull request merged**
