### PR TITLE
Design With FontForge: Japanese Translation

### PR DESCRIPTION
**Pull request by J1-takai**
Just completed the Japanese translation of DESIGN WITH FONTFORGE document. This is my first attempt of GitHub work as well as a document translation. Hope it works OK.

### CODE REVIEW

**Comment by JoesCat** [comment]
Hi @J1-takai,
This is a very LARGE pull request - It must have taken a long time to put together.

Thank you for your time and effort putting this together.

I started looking at this and noted 2 things that need fixing.
1) Starting with the folder, I noticed that you created a folder "ja-JA", this is almost okay, but to follow the standards, we can go look and see what it should be.
[Locale for Japan](https://www.google.com/search?q=locale+code+for+Japan), and we really should set the folder as "ja-JP".
2) Each page has a line which needs to be changed from "bookpage" to "book_page_ja-JP". You can compare this with fr-FR/Introduction.md or zh-CN/Introduction.md

There is also a third thing that I think you may want to fix, which is the "author/commit" email. There is two ways to do this, the easier way is to change your homepage settings and add an email. then when you create a Pull-Request and the many commits you made, github will use the email you set for you homepage for the Author/Committer emails instead of an obfuscated email that only tracks back to github and doesn't give you recognition anywhere else. You can always remove your homepage email address again, after doing the commits if you do not want to have your email shown on your homepage.
The other way to do this is a bit more technical, and as per your homepage stating you're retired and a non-programmer, we could probably skip this, but if you want to learn how to do it, it looks like this [command-line-instructions](https://github.com/JoesCat/xinvaders3d/pull/2#issuecomment-2094685074).

If you would rather I take care of all these, let me know (just provide me with an name+email to put on the commits), but otherwise, it looks basically as we close this Pull-request, and you start a new pull request, using folder ja-JP, and  inserting all the files you already created, but add the fixed bookpage_ja-JP to all the pages.
Changes

...and once again - Thank You - this is a very impressive PR.

**Comment by J1-takai** [comment]
Hi @JoesCat ,

Thank you very much for your detailed checks and kind comments. I've made some corrections as mentioned above:

1. the folder "ja-JA" is renamed as "ja-JP".
2. "bookpage"/"homepage" lines in each document pages are updated to have "_ja-JP" at the end of those terms.
3. also corrected the links in the documents (i.e.  ../ja-JP/..) .
4. Above data are now committed and pushed. 

As for the email setting, I tried to add the second email address for communications, but I somehow could not show it visible (public) at my repository. 

Can I start a new pull request now?

rgds

**Comment by JoesCat** [comment]
> Thank you very much for your detailed checks and kind comments. I've made some corrections as mentioned above:

Yes - I noticed - thank you.

> As for the email setting, I tried to add the second email address for communications, but I somehow could not show it visible (public) at my repository.

Yes, it is an expected behaviour that you cannot edit the email on committed PRs. There is a way around it, but it gets technical. The easier way is to start a new pull request.

> Can I start a new pull request now?

...on second thought, let us avoid this, and you continue doing the same method you are doing now (It appears I'll have to do the more technical method instead).
I took a look at your repository, and noticed that your edits are all along the same master branch (gh-pages is considered the tree trunk for this repository). [J1-takai:gh-pages is using same tree-trunk as fontforge:gh-pages](https://github.com/J1-takai/designwithfontforge.com/branches). The right method was to create a new "branch", example, branch called "japan", and then add pull request there. If there was problems, you could cut this branch and make another branch. This "branch" method allow for multiple developers to work in parallel without affecting each other too. ....but, since this is what it is now, better to finish-up what we can now, and work with that instead.
Let's continue what you have, and we'll merge that instead.
If you want to have your email inserted - just type it here (or email me at digital at joescat dot com), I'll add it into the commits the more technical way.

...okay, there's a couple more files that are worth adding too, if you can.
In directory "_includes", there are files called "footer.html" and "header-masthead.html". Can you  copy these and create files "footer_ja-JP.html" and "header-masthead_ja-JP.html". Use the other files present as examples as to what to edit for these new files.
In directory "_layouts", can you please copy "bookpage.html" to "bookpage_ja-jP.html, and also "homepage.html" copied to "homepage_ja-JP.html". You can use the other files as examples too.

No need to rush or hurry, as I need to do some other things in the meantime....
Thanks!

**Comment by J1-takai** [comment]
Thank you @JoesCat for your new suggestions and sorry for all the troubles I've caused due to my whim to have a Japanese version.  (I should have made a pdf version instead - much easier to handle!).

Now I created four *_ja-JP.html files as suggested above - I hope I have done them correctly.

As for the repository issue, I better not dare to try it by myself as I am almost certain that I mess up the situation further.  I’d like to leave it to a specialist.

Please let me know what I should do next (yes, no rush, and whenever you have time to spare for me). At this moment, I am working on the Tutorials in Japanese in the pdf format - I took the easy road this time!!

**Comment by JoesCat** [comment]
> Thank you @JoesCat for your new suggestions and sorry for all the troubles I've caused due to my whim to have a Japanese version. (I should have made a pdf version instead - much easier to handle!).

Actually, you did the right thing here by supplying your translations. There will always be some technical problems to fix, but that is part of the process. The main task, which is making a translation is done. Give yourself a pat on the back for a job well done - it is not an easy thing to do, but you did it - good work - Thank you!

> Now I created four *_ja-JP.html files as suggested above - I hope I have done them correctly.

Excellent! these are tiny details eaily overlooked - thank you for doing these too.

> As for the repository issue, I better not dare to try it by myself as I am almost certain that I mess up the situation further. I’d like to leave it to a specialist.

Yes! this part is a bit more technical - and understandably as a non-programmer, it is an issue that we should not insist on, so we work around this. :-)

> Please let me know what I should do next (yes, no rush, and whenever you have time to spare for me). At this moment, I am working on the Tutorials in Japanese in the pdf format - I took the easy road this time!!

Some of my delay was trying to find a workaround for the tools mentioned on the README, like jekyll and grunt since my computer doesn't have those tools. I think I've found a workaround to that.
The other delays is life: family, friends, work,sleep,eat,etc.. the usual things everyone has to contend with :-)

I'm looking at the gitK email....seems I made an error thinking it was an obfuscated github email, and now realizing I made an error since it's not an obfuscated email....just unexpected for me to see "jt.x-l88.4989" as part of an email - my error.
(FYI: github uses numbers for creating obfuscated emails).

Re-opening your pull request so it could be merged.
(It did not need to be closed - it is excellent work - thanks).

**Comment by JoesCat** [comment]
Hi @J1-takai,
More requests - no need to hurry:
In directory ebook there is a file called "create_books.sh".
About 12 lines down you will see a line that shows:
BOOKS="en-US zh-CN fr-FR"
this could be modified to
BOOKS="en-US zh-CN fr-FR ja-JP"

Then there is a directory called "honkit-en-US"
If you can duplicate the entire directory to "honkit-ja-jP"

Inside the new "honkit-ja-JP" are a few files of interest.
book.json has 2 lines: title and description that need translations. You can look in directory "honkit-zh-CN" or "honkit-fr-FR" for examples.
language would be "ja"
paperSize: a4 is European, but may be best to work with this on first draft, I'm not sure yet. eg: [paper sizes](https://www.google.com/search?q=paper+size+japan)

Then there is file SUMMARY.md - you could use the honkit-fr-FR and honkit-zh-CN examples to help.

Inside the subdirectory styles, there is nothing to edit. leave the ebook.css file as-is.

**Comment by J1-takai** [comment]
Hi @JoesCat 

Thank you for your support and  assistance. Just finished the ebook related files.

1. create_books.sh: added "ja-JP"
2. honkit-ja-jP: created the ja-JP directory and the two related files; book.json and summary.md.
3. "Revised" two cover images (regular & small ones). These image files were kept in tact, because I have no skills to edit graphics. I am still totally unfamiliar with Inkscape (I tried but no expected results came true), so I gave up to handle the two *_template.svg files and decided to add the "cover".jpg files some Japanese wordings (like "Japanese version" etc.) on them instead.  The image quality may not be good enough compared to the originals.

Please let me know if any other modifications are required.

kind regards - J. Takai

**Comment by J1-takai** [comment]
Sorry I must have clicked the wrong button. "Reopen" requested.

**Comment by JoesCat** [comment]
Thank you @J1-takai for your efforts on this.

This is a very large Pull Request! Will merge it in now.
Also will try to tackly some other PRs and issues, but hopefully sometime within next two weeks or so, we'll all see the results of your work.

Thanks again!
Joe

**Comment by J1-takai** [comment]
Understand and thank you for your great help. Much appreciated. 

J.Takai

**Comment by JoesCat** [comment]
FYI - if you want another "large" project, you might want to start a repo with this textfile [NamesList.txt](https://www.unicode.org/Public/UNIDATA/NamesList.txt).

This would eventually apply towards [libuninameslist](https://github.com/fontforge/libuninameslist). This is the current popularity for [libuninameslist](https://repology.org/project/libuninameslist/versions).

If you need an example to compare with [ListeNoms.txt](http://hapax.qc.ca/ListeNoms-15.1.0.txt).

NOTE: It is a very large file, so go as far as you want, start with the characters that would make most sense to you first, like the Japanese char set, and the ASCII chars, then others if you choose to continue as far as you want.

Charset 0000...FFFF are about the most stable, while new chars (and emojis) are put in 10000...1fffff

...thanks again for you work on this PR.

**Comment by J1-takai** [comment]
Outlook for Androidを取得差出人: Joe ***@***.***>送信日時: 木曜日, 6月 13, 2024 10:07:38 午前宛先: fontforge/designwithfontforge.com ***@***.***>CC: Junichi TAKAI （たかい　じゅんいち） ***@***.***>; Mention ***@***.***>件名: Re: [fontforge/designwithfontforge.com] Design With FontForge: Japanese Translation (PR #239)
Thank you @J1-takai for your efforts on this.
This is a very large Pull Request! Will merge it in now.
Also will try to tackly some other PRs and issues, but hopefully sometime within next two weeks or so, we'll all see the results of your work.
Thanks again!
Joe

**Comment by J1-takai** [comment]
Hi @JoesCat 

Thanks to your suport, Japanese version of "Design With FontForge" is nicely merged to the website. However, I noticed that I made a mistake in the Index.md file where I forget to set Locale info to "ja-JP" (due to this, if a user clicks "JP edition", it still jumps to "US Index Page". 

The file was modified and uploaded. Please update the file. Sorry for bothering you so many times.

J. Takai

**Comment by JoesCat** [comment]
Hi @J1-takai - it took a little bit of searching to figure-out what was fixed, but I see it now [index fix](https://github.com/J1-takai/designwithfontforge.com/commit/d411242b561efafccfbc1eeb55449d5aecee72c3). I also note that it causes a few files in directory ebook to get deleted too, which is a bit too early for this yet.

I more-or-less posted a commit in your name that does similar effect (but without deleting the ebook files).

Once again, I hope to have a little help from you.
There are several updated pages for ja-JP I hope you can fix/improve, but first, this is easier if your repository is up to date, so you can create a new pull request for the fixes you see that are needed.

Looking at your repository, and due to using the main tree-trunk branch instead of a new-branch, your repository will be out of alignment with the current updates.
1ahead87behind

I think, the easiest way to resolve this (from your point of view) would be to delete your existing repo, and then import a fresh clone of designwithfontforge to bring you up to date. This way, your repo is once again, in-sync with the main designwithfontforge repo, and you will be able to create a fresh pull-request.
No worries about deleting your repo, as your earlier pull-request is already merged with the main designwithfontforge.

- Pages four, six and seven have some added info can you translate these?
- Page 30, has a few more URL links added, I do not know if you want to edit those.
- Page 8 (General UI Introduction) we've made the GUI instructions look a little fancier, I do not know yet, if you like to do similar for the Japanese pages (see instruction 3).

Another question....
Would you recommend a good *.woff or *.woff2 font that can display Japanese better? I noticed that we are probably using a bitmap font when displaying Japanese, and it looks a bit pixellated when the font is large, so it must look a little horrible if printed to paper - you can see it here: 
pixelizing

**Comment by JoesCat** [comment]
Hi @J1-takai - I noticed a few days ago that you tried to create a "Design with Fontforge" repository. I created a mini-help-instructions so that it may help you. I've seen this problem many times over-n-over again with FontForge, as well as "Design with FontForge" as well as other repositories. I hope this helps: #253 If you find that it does help, that's great, as it will help others as well.

**Comment by J1-takai** [comment]
Hi @JoesCat - thank you for your "clairvoyance" and timely advice. Actually I tried a couple of times to "clone" the repository, but the first one was cloned in my PC (via vs code) and tried the second one to clone repo into my personal Github area (but its setting did not look light). With your Help Guide, now it seems that I could get back to the right track halfway (I still have to setup the VS code to connect this newly cloned branch/folk. (Your Help guide was so useful that I should prom this in Japan).

Sorry I have checked the previous issues (newly added info in the English version). I will check them once i am fully on track.

The second point on jagged/pixely font edges - yes, I would like to have smooth scalable fonts for JP version too, but I have no knowledge on *.woff fonts... Please advice what I need to do for this issue.

J, Takai

**Comment by JoesCat** [comment]
> Hi @JoesCat - thank you for your "clairvoyance" and timely advice. Actually I tried a couple of times to "clone" the repository, but the first one was cloned in my PC (via vs code) and tried the second one to clone repo into my personal Github area (but its setting did not look light). With your Help Guide, now it seems that I could get back to the right track halfway (I still have to setup the VS code to connect this newly cloned branch/folk. (Your Help guide was so useful that I should prom this in Japan).

Glad it helped :-)
Often a picture is worth more than 1000 words.

> Sorry I have checked the previous issues (newly added info in the English version). I will check them once i am fully on track.

I didn't get too far, next page to go is "Drawing with Spiro", and onwards.

> The second point on jagged/pixely font edges - yes, I would like to have smooth scalable fonts for JP version too, but I have no knowledge on *.woff fonts... Please advice what I need to do for this issue.

It appears it has already been resolved. I ran a live distro of Ubuntu 24.04 to test-out some jekyll and it seems the fonts look a lot nicer there. Japanese and also noticed Chinese too. I'll need to change "Design with Fontforge" to use that font instead.

**Pull request merged**
