### PR TITLE
Translation of Simplified Chinese

### PR DESCRIPTION
**Pull request by JohnWong**
After some days and nights, I've made a translation of simplified Chinese. Current homepage of the site contains pages of different languages. I've fixed this issue by adding localized html templates. I've also add links to page header to switch language. Here is what a page of Chinese translation looks like.

image-11-24-14-at-11 50-pm

Hope it would help. Mail me (huangxiaozhe1988@gmail.com) if you want.

### CODE REVIEW

**Comment by davelab6** [comment]
WOW!!

**Comment by zerng07** [comment]
Impressive! 

It is better to use "簡體中文版" instead of "中文版" for zh-CN to distinguish with zh-TW on language switch.

**Comment by JohnWong** [comment]
OK.

**Comment by JoesCat** [comment]
Would you like to add a Chinese translation here (desktop description):
https://github.com/fontforge/fontforge/blob/master/desktop/fontforge.appdata.xml

"C" is for default English language.
You will notice lang="??" for other languages.

NOTE:This html text file is easy to edit using a utf8 capable text editor.

**Comment by JohnWong** [comment]
Absolutely Yes. I will have a try.
A little question. Should I use zh_CN for simplified Chinese?

**Comment by adrientetar** [comment]
> Should I use zh_CN for simplified Chinese?

Legacy IBM encodings seem to use this convention, I think this should do it.

**Comment by JoesCat** [comment]
On November 25, 2014 04:21:46 AM Xiaozhe Huang wrote:

> Absolutely Yes. I will have a try.

That was great.
Thank you.

zh_CN was a good choice - You want to maximize the access to as many 
readers as you can.

If you want to continue, there are more places that can use attention.
Do as little or as much as you want.

1) In directory po, there are zh_CN files which could probably be updates 
since FontForge has grown since the last time these files were last modified.
I also found it easier for myself to use a text editor, but this is up to 
you if you want to do that. Update as much as you want:
https://github.com/fontforge/fontforge/tree/master/po

2) This is much more challenging In directory doc/html (and 1 is considered 
more important to update first), if you want to create a Chinese 
translation, you can add a cn directory similar in concept to de or ja 
here:
https://github.com/fontforge/fontforge/tree/master/doc/html
You can check your files using a webbrowser, like you did with 
designwithfontforge
The Makefile.am will need to be modified to include the cn directory.
This file also will need to be modified at about line 218 so that you can see 
the cn directory if you press help in the graphical FontForge:
https://github.com/fontforge/fontforge/blob/master/fontforgeexe/uiutil.c
As you may notice, this would be a big project if you completed it.

**Comment by JohnWong** [comment]
I am glad to make effort. I will try it soon.

**Pull request merged**
