### PR TITLE
Update What_Is_a_Font.md

### PR DESCRIPTION
**Pull request by keevee09**
Just two minor (pedantic) suggestions in grammar.
Par2: "...the creation <of> a wonderful collection..."
Par4: "...is that to <a> very large extent..."

### CODE REVIEW

**Comment by davelab6** [comment]
AWESOME!!! Thanks @keevee09

**Comment by keevee09** [comment]
No problem Dave, glad to be helpful in a small (pedantic) way :)

**Comment by davelab6** [comment]
I'm curious about what you think is missing from the site so far? :-)

**Comment by keevee09** [comment]
Hi Dave,

I haven't read it thoroughly as yet but will keep you informed as I read
through. My initial opinion is quite favourable (I'm not street-savvy
with modish superlatives so 'quite favourable' is a rave review to
people who know me). It is stylish, well-sectioned, informative and
knowledgeable.

I've had some issues with installing FontForge on my system but catering
for every scenario at that level is beyond any book. I'm running
xubuntu-12.04 on this laptop (the ubuntu repositories are becoming quite
stale -- no, not stable -- hence the choice to install from source). For
the windows users I have found this site:
http://www.mpetroff.net/software/fontforge-windows/
which offers pre-built binaries. I've downloaded the binaries, both with
and without Python support to test them on a Windows PC.

I've dug in and got spiro installed as per your instructions. Before
reading your chapter on installation I had failed to install the version
of spiro listed on github - it seems to be missing an '-lm' somewhere
but I haven't tracked down just where yet.

Thank you for such a great resource. I remain an amateur that may be
"just browsing" but still appreciates the effort and charity that goes
in to such a project.

Cheers,
Chris

PS :-

I spotted one more mistake, but am unsure of the correction so will just
quote it here for you to check over.

From "Creating Your Type's DNA", 6th paragraph:

"The foundry Type Together uses this set themselves ,and when they teach
type design."

**Comment by keevee09** [comment]
... I've got spiro working now :)

**Comment by davelab6** [comment]
http://openfontlibrary.org/en/guidebook/how_to_install_fontforge should be up to date for compiling from source

**Comment by keevee09** [comment]
Ahh thanks, that method will include libuninameslist, libzmq and czmq
which I haven't included in my current build.

**Comment by davelab6** [comment]
Really we should add Ubuntu 12.04 to https://build.opensuse.org/project/show/home:monkeyiq:fontforge @monkeyiq

**Comment by keevee09** [comment]
I've had the good fortune to trial FontForge on OSX10.8.5, xubuntu12.04
and windows7. So far the mac setup is my favourite, running under
XQuartz it is smooth and the windows open and are sized consistently
without having to adjust any configuration files. The icon scheme is
also simple to interpret... a pity it isn't my mac!
 Xubuntu is crashing-to-desktop seemingly at random but I suspect it is
something to do with the windowing system as it is usually shortly after
I close a window or swap between windows.
 Windows7 seems stable so far. My only small gripe is that the windows
open at far corners of the monitor when starting FontForge; it's just a
mild nuisance needing to drag them to sensible positions on-screen. So
far it hasn't crashed.

I've made my way through the first few steps of creating a glyph from
your book. I enabled View>Show>Fill which wasn't set by default on any
of the OS's. The tutorial is otherwise straightforward and set at a good
pace for the level of novice learning an advanced piece of software.

**Comment by JoesCat** [comment]
On November 1, 2013 02:37:14 PM keevee09 wrote:

> ... I've got spiro working now :)

Did you have to do anything special to get it working?
I noted that you mentioned -lm earlier.

**Comment by keevee09** [comment]
I had been trying to compile the version available from the Git
repository here:
https://github.com/fontforge
and it was failing on sincos etc - i.e. -lm was missing somewhere from
the test folder.

The version from:
http://libspiro.sourceforge.net
works. This is the version that you point to in your book.

So, to sum up your instructions worked for me. As to the crash, I've run
fontforge in gdb and posted the output of a repeatable segfault to the
developers' mailing list.

For your interest here is the output after starting fontforge, with the
glyph window open and having opened the freehand dialogue and drawn a
simple curve it segfaults when I close this dialogue window:

---

slarty:~/CODE/source/fontforge/git_fontforge/fontforge$ gdb fontforge
GNU gdb (Ubuntu/Linaro 7.4-2012.04-0ubuntu2.1) 7.4-2012.04
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later
http://gnu.org/licenses/gpl.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "i686-linux-gnu".
For bug reporting instructions, please see:
http://bugs.launchpad.net/gdb-linaro/...
Reading symbols from /usr/local/bin/fontforge...done.
(gdb) run
Starting program: /usr/local/bin/fontforge
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/i386-linux-gnu/libthread_db.so.1".
Copyright (c) 2000-2012 by George Williams. See AUTHORS for contributors.
 License GPLv3+: GNU GPL version 3 or later
http://gnu.org/licenses/gpl.html
 with many parts BSD http://fontforge.org/license.html. Please read
LICENSE.
 Executable based on sources from 10:15 NZDT  2-Nov-2013-ML-D.
 Library based on sources from 10:15 NZDT  2-Nov-2013.
 Based on source from git with hash:1e8126820ccbf94b431dd70acdb2ef72019a3997
PythonUI_Init()
copyUIMethodsToBaseTable()
SplineFontPieceMeal() going unhinted...
XXXXXX as:0  ds:0
XXXXXX h:0
XXXXXXX charselectorh:35
CVPreserveState() no_windowing_ui:0 maxundoes:12
CVPreserveState() dm:2 layer:1 new undo is at 0x837f648

Program received signal SIGSEGV, Segmentation fault.
GDrawDestroyWindow (w=0x41) at gdraw.c:113
113     (w->display->funcs->destroyWindow)(w);
(gdb)

---

I'll wait to hear back from the developers on this. Meanwhile I'll
continue on my windows7 machine.

**Comment by keevee09** [comment]
Hmmm, just tested the freehand dialogue on windows and get a segfault
too. That is the first crash on windows for me.

**Comment by davelab6** [comment]
Is this the old 2012 mpetroff windows build?

@monkeyiq prepared a new windows build that is better, which we will sell in order to make his development sustainable. Drop me an email at dave@lab6.com and I'll let you know where to grab it from :)

**Comment by davelab6** [comment]
@keevee09 could you make a screenshot of the app on xubuntu just before the crash? Or, perhaps you can duplicate https://github.com/fontforge/fontforge/blob/master/fontforge-debug-lldb.sh and https://github.com/fontforge/fontforge/blob/master/fontforge-debug-lldb-script.txt and adjust them for gdb so that we get a stack trace, then it will be easier to fix this crash :) 

> I spotted one more mistake, but am unsure of the correction so will just quote it here for you to check over. From "Creating Your Type's DNA", 6th paragraph: "The foundry Type Together uses this set themselves ,and when they teach type design."

Fixed! https://github.com/fontforge/designwithfontforge.com/commit/bddc10e776674be78b5ea665e7cbf360a16b1de6

**Comment by keevee09** [comment]
This is the freehand crash I assume?
I checked it on Window7 and OSX-10.8.5 and experienced the same seg-fault.
I'll follow up and get back to you on this. I'm not sure if I can trace
the error on Windows or the OSX but will see what I can do.

**Comment by keevee09** [comment]
After installing libspiro-master and reinstalling fontforge-master I can use the freehand dialogue on xubuntu-12.04 32bit (? was it something I missed before?).

It still occurs on OSX10.8.5 and Windows7-64, both Petroff's build and monkeyiq's.

What I do to reproduce the segfault on Windows7 and OSX10.8.5:
1. Open the  glyph editor
2. Double click the freehand button in the toolbox to open the freehand dialogue
3. Draw a simple curve
4. Click 'OK' button to close the freehand dialogue

I'll look at debugging it on Win7 - I have no experience with coding on a windows machine so I may be some time... 
...running gdb:
<gdb>target exec fontforge.exe
gives me the error:
[Inferior 1 (process 2256) exited with code 01]
... so I have some learning to do.

The OSX machine is not mine so I'll need to seek permission before installing debuggers etc.

**Pull request merged**
