### PR TITLE
Update Menu title in General_UI_Introduction

### PR DESCRIPTION
**Pull request by ahangarha**
image

### CODE REVIEW

**Comment by JoesCat** [comment]
While looking at [Installing Fontforge](http://designwithfontforge.com/en-US/Installing_Fontforge.html) This change would seem to mix-up theming between GUI commands and command-line instructions.
We should probably leave the `quoted commands` for command-line just to keep the theme consistent.

**Comment by ahangarha** [comment]
Okay. I will update the PR soon

**Comment by ahangarha** [comment]
I changed the format to be bold.

We need to define some rules for such things. There is not standard for it. Sometimes we bold them, sometime we use Italic and sometimes we leave it unstyled.

**Comment by JoesCat** [comment]
True, seems there is no standard to show GUI commands.
We should surround your instructions with nbsp to avoid breaking the sequence depending on if it gets printed on _Letter_ or _A4_ or a different sized page.

Do you think adding Italics helps? or surrounding the commands in a different colour scheme helps, or hinders the command?

I think the nbsp is of value since this could end-up being lengthy....but if it is too lengthy, it needs to be broken-up in the right locations. I spot a location that is probably a must...
**Window > New Metrics Window**, or **Metrics > New_nbsp_Metrics_nbsp_Window**.

**Comment by JoesCat** [comment]
Including this for reference:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/kbd

maybe a bad idea:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/menu

**Comment by ahangarha** [comment]
I think the content should be as markdown as possible. Any further issue should be handled by the parser.

But since you have more experience here, you define the standard. But I think Italic is better than bold. I used bold here because it is used more than Italic.

Also the `menu` HTML tag is not meant for this purpose.

**Comment by JoesCat** [comment]
Italics makes sense.

> But since you have more experience here, you define the standard. But I think Italic is better than bold. I used bold here because it is used more than Italic.

Only picked this up in June, and I have yet to read through the entire book ;-P

...will go with bold wrapped in italics here, and fix other references along the way...

**Comment by JoesCat** [comment]
I think it could probably use some colour :-/

**Pull request merged**
