### PR TITLE
Added quick nav at the bottom of article, implemented grunt workflow for compressing images & header links are now linked to page in corresponding language.

### PR DESCRIPTION
**Pull request by chakler**
I've added a quick navigation at the bottom of every article in all three language to give a better usability. This also solved issue #73.

However in order to make this work, I have to remake the page-order mechanism of the site. So now the pages will be ordered by a prefix in the file name. e.g. `01-Introduction.md`

I've also implemented Grunt for compressing content images, the workflow is documented in README.md. I'm not sure if I've understand #40 correctly, but this should solve the issue. :smiley:

### CODE REVIEW

**Comment by davelab6** [comment]
Wow! Awesome!

I'm curious why the page.weight couldn't be used for ordering in the footer?

**Comment by chakler** [comment]
Because in order to get the previous and next page info, the script needs a list/array of pages so it will be able to scan through it in both ascending and descending order.

However, Liquid is not very good at altering arrays(there are no good way of adding item inside an array). So my only choice of making the quick nav work is to let Liquid sort site.pages by the file name, this way we can get a list of pages in order at ease. The list is also very reusable(Used in prev, next and list of pages in aside).

Also, the compiling time has become a lot faster(from around 60s to around 5s). I think it's because Jekyll is processing less logic and less matching.

Is there a reason why the pages are ordered in weight?

**Comment by JohnWong** [comment]
Currently, weight is used for sorting pages. See https://github.com/fontforge/designwithfontforge.com/blob/gh-pages/en-US/index.md

Using file name to sort pages is a better way. For example, rename the 1st chapter to "01_What_Is_a_Font.md".

**Comment by chakler** [comment]
@JohnWong Yes I do understand weight is now being used for sorting pages, but are there any reasons why weight is chosen over using file name for sorting? I may have missed some reasoning behind.

And yes, I think using file name to sort pages gives the directory some sort of clarity. It has already been implemented in my fork. :smiley:

**Comment by JohnWong** [comment]
Sorry, I answered your question without checking your commits. I agree with your idea and can not find any side effect. Weight is already used when I joined this organization. So you may wait for @davelab6 's answer.

**Comment by chakler** [comment]
No problem, John! :ok_hand:

**Comment by davelab6** [comment]
I just think it looks a bit ugly :) I'm happy to merge this though, as
Liquid is limited

**Comment by chakler** [comment]
Ugly in terms of the file name/structure, or the url? If it's about the url, I think there's a way to fix it :smile:

**Comment by davelab6** [comment]
URL, yes :) Awesome

There is an edit this page link that assumes URL and filename map btw

**Comment by chakler** [comment]
Sadly I can't fix the URL issue properly because of our file structure. But good thing is I've found out Jekyll is now supporting sorting by weight, so now the sorting will be done by weight, with the method used in sorting by name.

I've also added some weight lists for reference purpose. so all the page weights will be documented. Documentation and guidelines are added to README.md.

**Comment by davelab6** [comment]
Thanks again!!! :)

**Comment by chakler** [comment]
No problem! I'm happy to help :)

**Pull request merged**
