### PR TITLE
Add General Introduction page

### LINKED ISSUE #85: Chapter 6.5 Introduction to the interface
It currently jumps directly from installing it to how to use the drawing tools. 

I think novice users would benefit from a more general introduction to the interface.

### PR DESCRIPTION
**Pull request by davelab6**
Resolves https://github.com/fontforge/designwithfontforge.com/issues/85

I'd like someone to review and merge :)

### CODE REVIEW

**Comment by larsenwork** [comment]
Looks good, although I'd maybe remove the "or Metrics, Window" since I think that menu item should be removed :wink:

I'll create an issue on FontForge soon that adresses that and other issues with the current menu :smile:

**Comment by davelab6** [comment]
> since I think that menu item should be removed :wink:

HAHAHA :) I know its duplication, but, having taught 100s of people in over a dozen workshops in the last couple of years, I know for sure that many many users **EXPECT** the metrics window to be called from the Window menu.

However, redesigning the order of menus is very _low hanging fruit_ as its won't take much for @frank-trampe or @adrientetar to help us implement it if we have a precise plan for what we want to change. And it will make FontForge substantially better.

**Comment by davelab6** [comment]
> I'll create an issue on FontForge soon that adresses that and other issues with the current menu :smile:

I started https://github.com/fontforge/fontforge/issues/2257 to brainstorm this :)

**Comment by larsenwork** [comment]
Hehe, sorry if I got it wrong. I obviously meant it should on be in the window menu. 
So window -> metrics stays
Metrics -> window bye bye

**Comment by davelab6** [comment]
> window -> metrics stays
> Metrics -> window bye bye

Sorry, you were clear, I got it wrong, but, it doesn't matter and I insist to have both :)

Just as many users expect the metrics window to be called from the Window menu as from the Metrics menu.

**Comment by larsenwork** [comment]
:/ have the same menu item twice is...more than you'd expect a menu item to be somewhere you'd expect all menu items to have one unique function. Maybe after a menu cleanup people can easier find things?

**Comment by davelab6** [comment]
Maybe. I'm willing to remove it as part of a menu overhaul and then test it out in a workshop and see what a couple dozen people do in practice :) 

Although, I do see the logic in having the option in both menus. Window, Metrics / Metrics, Window :)

**Comment by davelab6** [comment]
I guess users never think to go to the Window menu is because on Mac this menu is rarely used to call up a window, its mainly used for window management, and thus rarely used:

screen shot 2015-05-05 at 8 18 54 pm

**Pull request merged**
