### PR TITLE
Update Spacing_Metrics_and_Kerning.md

### PR DESCRIPTION
**Pull request by davelab6**
Thanks to Martin B. Brilliant for the additional information!

### CODE REVIEW

**Comment by jrbastien** [comment]
"So, this kerning information is founding by go to " ---> "So, this kerning information is found by going to "
"For example in the screenshot above, 2 classes " ---> "For example in the second screenshot bellow, 2 classes "

**Comment by davelab6** [comment]
Fixed, thanks!

**Comment by jrbastien** [comment]
> If you want to kern references along with the originals, choose classes.

When we say "references" I think we are talking about other glyphs that use the same base glyph.  Correct? Perhaps an explanation is needed before using the term reference.  Or at least a reference to the [Diacritics and Accents](http://designwithfontforge.com/en-US/Diacritics_and_Accents.html) chapter.

And in fact, after rereading, in the 2 consecutive screenshot, the first does not belong there anymore.  I believe it can be removed.  But perhaps this entire text did not need to be shuffled around.  I tested it when translating and it was working.  The only thing that could have been added was the sentence about the references.

**Comment by davelab6** [comment]
Please go ahead and make a PR, I gotta sleep =)

**Pull request merged**
