### PR TITLE
French translation

### PR DESCRIPTION
**Pull request by jrbastien**
Proudly presenting "Design **_avec_** FontForge".

design avec fontforge

@davelab6 (who seems to be the maintainer of this guide):

- This is the complete translation and it matches the latest version of the French po.
- I have created 63 new screen shots showing the interface in French
- We should perhaps move the images folder out of US.  Otherwise, this requires pointing the images to two different locations (one for the images not requiring new screen capture and another location for the images showing translations).  It also requires creating a Grunt script for each folder.  I personally put all my images under ../US/Images and named them -fr-FR.png.
- Talking about the grunt script, it was very difficult to get it running on Ubuntu 16.04.  I had to add dependencies to package.json.  If you think this will create problem on different systems, you can remove them.
- Notice that I have created some drawing to show the new buttons.  If you want them in the US version just let me know.  https://github.com/jrbastien/designwithfontforge.com/blob/gh-pages/en-US/images/transform_tools_labelled-fr-FR.png
- I have used Ubuntu Ambiance for the screen shots (which is not the nicest theme) but they can be re-captured by a bigger audience than if I had used a very specific theme.  
- To do: create a subtitles file for the video describing the FontForge interface and have it uploaded to Youtube.
- To do: Gitbook for the ebooks.  There was no instructions so I did not do them.
- I see other translations awaiting to be merged.  I don't know if they are complete but if you need help to include them into a single pull request, just let me know.
- And last but not the least, I have taken 4 pages of notes for small problems found in the US version (invalid hyper-links, text not in markdown creating display issues, part of text missing, etc..).  I will probably make these corrections once this pull request is merged.

Thanks for your attention.  This translation will provide a most needed documentation for the French community.

### CODE REVIEW

**Comment by davelab6** [comment]
Amazing work!!! 🌋🌋🌋

**Comment by jrbastien** [comment]
Thanks.  But really hats off to the autors of this guide.  I keep refining my translation but it is ready for prime time.  Any idea when you will have a chance to merge it?

**Comment by davelab6** [comment]
Should `Gruntfile (copie).js` be included?

**Review by davelab6 — APPROVED** [review]
Looks great!

**Comment by jrbastien** [comment]
Oups, Gruntfile (copie). js should not be included.  It was a copy I took when I was generating the images in a fr-FR/images.  I decided to move them back to the us-EN/images folder and added a suffix fr-FR.

**Comment by davelab6** [comment]
@jrbastien nice! I sent you an invite to the fontforge 'website' team, you are welcome to merge this when ready :) Great job!!

**Comment by jrbastien** [comment]
Thanks Dave.  These are big responsibilities.  I will re-read and re-test all of this again before merging.

**Comment by jrbastien** [comment]
@davelab6, I'm having an issue after the merge.  There is an additional entry at the beginning of the index that points to the weightlist.  This is doing this for all languages.  I have checked and these weightlists are not included in the language folders so I don't understand how it get there in the index.

selection_150

The index that gets generated has this entry:

```
<li>
        <a href="/en-US-weightlist.html">
          
        </a>
      </li>
```
Do you know who could help? Perhaps a restart of the Jekyll server is needed?

**Comment by davelab6** [comment]
> Perhaps a restart of the Jekyll server is needed?

The site is hosted at pages.github.com so I can't restart it like that... 

I'm not sure exactly what the weightlist page is; I thought the weights were in the frontmatter.

**Comment by davelab6** [comment]
Looking at https://github.com/fontforge/designwithfontforge.com/commit/cc4fd7df53c129cd56383e97457aa1fd66d69b52 the weightlist page seems purely for documentation / easy reference purposes.

**Comment by jrbastien** [comment]
Looking at the code for how the index get built:

```
<ol class="rectangle-list">
  {% assign pageList = site.pages | sort: 'weight' %}
  {% for p in pageList %}
    {% if p.path contains 'en-US' and p.title != page.title %}
      <li>
        <a {% if p.url == page.url %}class="active"{% endif %} href="{{ p.url }}">
          {{ p.title }}
        </a>
      </li>
    {% endif %}
  {% endfor %}
</ol>
```
So yes path contains 'en-US" but it is not in the language folder. I notice that there is a "revert" button in this page but I'm not sure how reliable it is.

**Comment by jrbastien** [comment]
I have found a "ugly workaround".  I have renamed fr-FR-weightlist.md to fr-FR-weightlist.md.bak and it disappeared from the index.

Should I do the same for the other languages or hope that it is daily restarted?

**Comment by jrbastien** [comment]
So I took an executive decision.  I have renamed all the weightlists to .txt.  Problem is solved.  But I don't have this issue on my local installation so I suspect that a restart would have also corrected this.

**Comment by davelab6** [comment]
> I notice that there is a "revert" button in this page but I'm not sure how reliable it is.

No need to revert, I think - its okay to fix moving forwards :) 

> I have found a "ugly workaround". I have renamed fr-FR-weightlist.md to fr-FR-weightlist.md.bak and it disappeared from the index.
>
> Should I do the same for the other languages 

I wonder that we can fix this by adding frontmatter to the pages like this:

```
---
published: false
---
```

Or, we could exclude these pages in the `if` statement,

    {% if p.path contains 'en-US' and p.title != page.title %}

> or hope that it is daily restarted?

Github pages restarts/reruns jeykll on each commit

**Comment by davelab6** [comment]
> So I took an executive decision. I have renamed all the weightlists to .txt. Problem is solved. 

:)

> But I don't have this issue on my local installation 

Yes, I also found that :) 

> so I suspect that a restart would have also corrected this.

Not sure about this, as above

**Comment by jrbastien** [comment]
Okay, thanks for the pointers.  It was a bit of a panic yesterday.  I had managed to break something on my first commit! 

I will do some further tests this weekend and come up with a proper solution.  Changing the if statement makes sense.

**Pull request merged**
