### PR TITLE
Cleanup, update and fix backend – refactor Chapters 1–8

### PR DESCRIPTION
**Pull request by adrientetar**
- Refactor the backend, fix some botches (merge conflict in the stylesheet, for example…) and make config/README up-to-date
- Cleanup templates, cleanup/fix HTML tags misuses
- Refactor Chapters 1–8 (i.e. rewrite a few parts and use smart quotes) and wrap them to 100 lines (the rest is TODO)
- Fix various issues in some other pages and use HTML char entities
- Minor stylistic changes: make the text a bit darker for better contrast (and so better readability), reduce slightly the headers sizes to not harness the reader, reduce slightly the header text on small widths to fit the container, misc other changes
- Various refactorings

r? @davelab6

Closes #30.

### CODE REVIEW

**Comment by davelab6** [comment]
Amazing!

Added you to the FF website team! : ) https://github.com/orgs/fontforge/teams/website-team

**Comment by adrientetar** [comment]
Cool, thank you!

**Comment by JoesCat** [comment]
Cool - Yes it is!

That is certainly a lot of effort spent well.
Definitely deserves a thanks.
If you are still interested in updating FontForge, I'm fairly sure the program documentation could use a fresh look to see if some things can be fixed improved.
Inside the FontForge docs directory is an html directory which you might want to look at. You can ignore the "de"=German, and "ja"=Japanese subdirectories...or if you have a language interest, we can add an "fr"=French subdirectory.
Another place to check is the po directory and see if the French is up to par.
I'm just mentioning this since I notice that your location is France :-)

These are text-editting ideas above since I noticed you've focused mainly on text, not code.
Please don't do any of the suggestions above unless you want to - however - Thanks for your efforts!
Joe

**Comment by adrientetar** [comment]
> I noticed you've focused mainly on text, not code.

I’m just getting started creating fonts, hence that PR (it really lacked contrast to be properly readable) – I will probably push some more things later on. :)

**Comment by JoesCat** [comment]
You found something that could be fixed.
You fixed it.

That puts you well above 99% of the crowd.

Thanks!

**Pull request merged**
